language: java
jdk:
  - openjdk17

services:
  - postgresql

before_install:
  - psql -c 'create database olattest;' -U postgres

before_script:
  - export MAVEN_OPTS="-Xms512m -Xmx1024m"
  - mvn compile -Pdocumentation,tomcat

script:
  - mvn clean test -Dwith-postgresql -Ptomcat

addons:
  postgresql: "9.4"

cache:
  directories:
    - $HOME/.m2
