language: java

# Choose the Java versions you want to test against
jdk:
  - openjdk11

# Specify the operating system you want to test on
os: linux

# Build script or commands to run before installing dependencies
before_install:
  - chmod +x gradlew  # Make gradlew script executable

# Install any dependencies or tools required for the build
install:
  - ./gradlew assemble

# Run tests
script:
  - ./gradlew test

# Optionally, you can specify the branches you want to build
branches:
  only:
    - main  # Build only the 'main' branch
    - develop  # Build the 'develop' branch as well, if applicable

# Cache Gradle dependencies to speed up builds
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
