language: java
jdk:
  - openjdk17

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE olattest;'

before_script:
  - export MAVEN_OPTS="-Xms512m -Xmx1024m"
  - mvn compile -Pdocumentation,tomcat

script:
  - mvn clean test -Dwith-mysql -Ptomcat

cache:
  directories:
    - $HOME/.m2
