language: java
jdk:
  - openjdk17

# Cache Maven dependencies to speed up build
cache:
  directories:
    - $HOME/.m2


# Setup postgresql and create the database
services:
  - postgresql

before_script:
  - psql -c "CREATE USER openolat WITH PASSWORD 'openolat';" -U postgres
  - psql -c "CREATE DATABASE openolat;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE openolat TO openolat;" -U postgres
  - psql -c "\c openolat openolat;" -U openolat
  - psql -f src/main/resources/database/postgresql/setupDatabase.sql -U openolat

# Commands to install dependencies and run tests
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn test -B
